Add required packages for Ubuntu

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -225,3 +225,13 @@ if [ "$with_ccache" ] ; then
 else
   qmake -r `osflags` $FLAGS "$@"
 fi
+
+if [ "$?" != "0" ]; then
+    case `uname` in
+        Linux.*Ubuntu.*)
+            echo "It looks like configuration failed. You may need:"
+            echo "sudo apt-get install llvm-3.4-dev libqt5svg5-dev libqt5webkit5-dev libqt5help5 libqt5opengl5-dev qttool5-dev qttools5-dev-tools doxygen festival festival-dev libxss-dev nodejs npm livlc-dev libvlccore-dev curl"
+            echo "(cd /usr/bin; sudo ln -s nodejs node; sudo ln -s llvm-config-3.4 llvm-config)"
+        ;;
+    esac
+fi
